apps/clients/urls.py
from django.urls import path
from .views import ClientList, ClientUpdate, ClientCreate, ClientDetails, ClientDelete


urlpatterns = [
    path("", ClientList.as_view(), name="client_read"),
    path("update/<int:pk>", ClientUpdate.as_view(), name="client_update"),
    path("new/", ClientCreate.as_view(), name="client_new"),
    path("details/<int:pk>", ClientDetails.as_view(), name="client_details"),
    path("delete/<int:pk>", ClientDelete.as_view(), name="client_delete"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.users.urls')),
    path('clients/', include('apps.clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.users.urls')),
    path('clients/', include('apps.clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clients/models.py
import re
from django.db import models
from contextlib import suppress

# from django.conf import settings
# from django.contrib.auth.models import User
from apps.core.places import STATES_BRAZIL
from django.utils.translation import gettext_lazy as _


CHOICE_CPF_CNPJ = (("cpf", "CPF"), ("cnpj", "CNPJ"))
CHOICE_SEX = (("undefined", "Selecione o sexo"), ("f", "Feminino"), ("m", "Masculino"))


class ClientModel(models.Model):
    name_corporate = models.CharField(
        verbose_name=_("Nome/Razão Social"), max_length=150, null=True
    )
    email = models.EmailField(
        max_length=254,
        unique=True,
        error_messages={"unique": "Este e-mail já está registrado."},
    )
    birth_date = models.DateField("Data Nasc/Abert", null=True)
    district = models.CharField(verbose_name=_("Bairro"), max_length=150, null=True)
    state = models.CharField(
        "Estados", max_length=25, choices=STATES_BRAZIL, default="default"
    )
    client_type = models.CharField(
        "CPF/CNPJ", max_length=10, choices=CHOICE_CPF_CNPJ, default="cpf"
    )
    cpf_cnpj = models.CharField(
        "CPF/CNPJ",
        max_length=20,
        unique=True,
        error_messages={"unique": "Este CPF/CNPJ já está registrado."},
    )
    sex = models.CharField(
        "Sexo",
        max_length=10,
        choices=CHOICE_SEX,
        default="undefined",
        null=True,
        blank=True,
    )
    address = models.CharField("Endereço", max_length=250, null=True)
    complement_address = models.CharField(
        "Complemento", max_length=20, null=True, blank=True
    )
    number_address = models.CharField("Número", max_length=10)
    photo = models.ImageField(
        "Imagem",
        default="default.png",
        upload_to="images/upload",
        null=True,
        blank=True,
    )
    rg = models.CharField(
        "RG",
        max_length=15,
        unique=True,
        null=True,
        blank=True,
        error_messages={"unique": "Este RG já está registrado."},
    )
    cep = models.CharField("CEP", max_length=15, null=True)
    # As posiçoes dos parametros importam.
    cell_phone = models.CharField(
        "Cell Phone",
        max_length=15,
        unique=True,
        null=True,
        blank=True,
        error_messages={"unique": "Este Celular já está registrado."},
    )
    phone = models.CharField(
        "Fone",
        max_length=15,
        unique=True,
        null=True,
        blank=True,
        error_messages={"unique": "Este Telefone já está registrado."},
    )
    city = models.CharField("Cidade", max_length=80, null=True)
    obs = models.TextField("Observações", null=True, blank=True)
    created_by_user = models.CharField("Criado por", max_length=30)
    update_by = models.CharField("Ultima atualização por", max_length=30)
    created_at = models.DateTimeField("Data de Criação", auto_now_add=True, null=True)
    update_at = models.DateTimeField("Data de atualização", auto_now=True, null=True)

    def __str__(self):
        return f"{self.name_corporate}".title()

    class Meta:
        db_table = "tbl_clients"
        verbose_name = "Client"
        verbose_name_plural = "Clients"
        ordering = ["-id"]

    def save(self, *args, **kwargs):

        # Remove hyphen and dot of CPF/CNPJ before save
        self.cpf_cnpj = re.sub("[^0-9]", "", self.cpf_cnpj)

        # Remove hyphen and dot of PHONE before save
        self.phone = re.sub("[^0-9]", "", self.phone)

        # Remove hyphen and dot of CELL PHONE before save
        self.cell_phone = re.sub("[^0-9]", "", self.cell_phone)

        # Remove hyphen and dot of CELL PHONE before save
        self.phone = re.sub("[^0-9]", "", self.phone)

        # Remove old photo after adding new
        with suppress(Exception):
            obj = ClientModel.objects.get(id=self.id)
            if obj.photo != self.photo and obj.photo != "default.png":
                obj.photo.delete(save=False)
        # Save
        super(ClientModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):

        # Before deleting the record, remove the photo for the record
        obj = ClientModel.objects.get(id=self.id)
        if obj.photo != "default.png":
            self.photo.delete()
        super(ClientModel, self).delete(*args, **kwargs)

apps/clients/forms.py
import re
from django import forms
from .models import ClientModel
from crispy_forms.helper import FormHelper
from django.utils.translation import gettext_lazy as _


class ClientForm(forms.ModelForm):  # pragma: no coverage
    class Meta:
        model = ClientModel
        fields = (
            "photo",
            "client_type",
            "cpf_cnpj",
            "name_corporate",
            "email",
            "birth_date",
            "district",
            "state",
            "address",
            "sex",
            "rg",
            "cep",
            "complement_address",
            "number_address",
            "cell_phone",
            "phone",
            "city",
            "obs",
        )

        widgets = {
            "state": forms.Select(attrs={"class": "form-select clients-form__states"}),
            "sex": forms.Select(attrs={"class": "form-select clients-form__sex"}),
            "client_type": forms.Select(
                attrs={"class": "form-select clients-form__client_type"}
            ),
            "birth_date": forms.TextInput(attrs={"type": "date"}),
            "email": forms.TextInput(attrs={"placeholder": "my-email@example.com"}),
            "cpf_cnpj": forms.TextInput(
                attrs={"class": "clients-form__input-cpf-cnpj"}
            ),
            "cell_phone": forms.TextInput(
                attrs={"data-mask": "(00) 00000-0000", "placeholder": "(00) 00000-0000"}
            ),
            "phone": forms.TextInput(
                attrs={"data-mask": "(00) 0000-0000", "placeholder": "(00) 0000-0000"}
            ),
            "obs": forms.Textarea(
                attrs={"placeholder": _("Escreva uma nota para este cliente")}
            ),
            "name_corporate": forms.TextInput(
                attrs={"placeholder": "Ex: Elvis Presley"}
            ),
            "rg": forms.TextInput(attrs={"placeholder": "Ex: 99.999.999-9"}),
        }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    # Limpa a mascara antes de fazer a verificação com o banco de dados.
    def clean_cpf_cnpj(self):
        data = re.sub("[^0-9]", "", self.cleaned_data["cpf_cnpj"])
        return data

    def clean_cell_phone(self):
        data = re.sub("[^0-9]", "", self.cleaned_data["cell_phone"])
        return data

    def clean_phone(self):
        data = re.sub("[^0-9]", "", self.cleaned_data["phone"])
        return data

apps/clients/views.py
import re
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.conf import settings
from django.views.generic import (
    ListView,
    UpdateView,
    CreateView,
    DetailView,
    DeleteView,
)
from .models import ClientModel
from .forms import ClientForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from typing import Any, Union
from django.utils.translation import gettext as _

# Get CEP
# def get_cep(instance, name: str, context: dict):
#     import requests
#
#     if instance.request.method == 'GET':
#         cep = instance.request.GET.get(name)
#         cep = re.sub("[^0-9]", "", cep)
#         data = requests.get(f'https://viacep.com.br/ws/{cep}/json/')
#         address_data = data.json()
#         if 'erro' not in address_data:
#             context["city"] = address_data['localidade']
#             context["uf"] = address_data['uf']
#             return address_data
#     return "CEP não encontrado."


def is_validate(obj) -> Union[Any, None]:
    """Função para verficar se o campo de pesquisa
    foi preenchido antes de mandar a busca"""

    if obj != "" and obj is not None:
        return obj.strip()
    return None


class ClientList(LoginRequiredMixin, ListView):
    template_name = "clients/listing.html"
    login_url = reverse_lazy("sign-in")
    model = ClientModel

    def get_queryset(self):
        records = self.model.objects.filter()
        q = self.request.GET.get("q")
        s_type = self.request.GET.get("s_type")
        data_number = self.request.GET.get("data_number")
        page = self.request.GET.get("page", 1)

        if data_number == "10":
            paginator = Paginator(records, 10)
        elif data_number == "25":
            paginator = Paginator(records, 25)
        elif data_number == "50":
            paginator = Paginator(records, 50)
        elif data_number == "100":
            paginator = Paginator(records, 100)
        else:
            paginator = Paginator(records, 10)

        try:
            records = paginator.page(page)
        except PageNotAnInteger:
            records = paginator.page(1)
        except EmptyPage:
            records = paginator.page(paginator.num_pages)

        if is_validate(q):
            if s_type == "cpf" or s_type == "cnpj":
                q = re.sub("[^0-9]", "", q)
                records = self.model.objects.filter(cpf_cnpj=q)
            elif s_type == "id":
                records = self.model.objects.filter(id=q)
            elif s_type == "name_corporate":
                records = self.model.objects.filter(name_corporate__icontains=q)
            elif s_type == "email":
                records = self.model.objects.filter(email=q)

        return records

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["media_url"] = settings.MEDIA_URL
        context["data_number"] = self.request.GET.get("data_number")
        return context


class ClientCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "clients/form.html"
    login_url = reverse_lazy("sign-in")
    # Usando o {{ perms.auth }} mostra os valores para usar no "permission_required"
    permission_required = "clients.add_clientmodel"
    model = ClientModel
    form_class = ClientForm
    # Apenas use o fields se não for usar o form_class
    # fields = '__all__'
    success_url = reverse_lazy("client_read")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["media_url"] = settings.MEDIA_URL
        context["PHOTO_ENABLE"] = settings.PHOTO_ENABLE
        return context

    def form_valid(self, form):
        # Ao criar, faz referencia ao usuário logado.
        form.instance.created_by_user = self.request.user.username
        form.instance.update_by = self.request.user.username
        # Resgata mensagem de sucesso caso seja criado.
        messages.success(self.request, "Salvo com sucesso.")
        return super().form_valid(form)


class ClientUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "clients/form.html"
    login_url = reverse_lazy("sign-in")
    permission_required = "clients.change_clientmodel"
    model = ClientModel
    form_class = ClientForm

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse_lazy("client_details", kwargs={"pk": pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["media_url"] = settings.MEDIA_URL
        return context

    def form_valid(self, form):
        # Ao atualizar, faz referencia ao usuário logado.
        form.instance.update_by = self.request.user.username
        # Resgata mensagem de sucesso caso seja atualizado.
        messages.success(self.request, _("Atualizado com sucesso."))
        return super().form_valid(form)


class ClientDetails(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = ClientModel
    login_url = reverse_lazy("sign-in")
    permission_required = "clients.view_clientmodel"
    template_name = "clients/form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["media_url"] = settings.MEDIA_URL
        context["is_details"] = True
        return context


class ClientDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = ClientModel
    login_url = reverse_lazy("sign-in")
    permission_required = "clients.delete_clientmodel"
    template_name = "clients/delete_confirm.html"
    success_url = reverse_lazy("client_read")

management/templates/clients/form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} Cadastro de Clientes {% endblock %}

{% block head %}{% endblock %}

{% block content %}

<!-- Loads -->
{% load client_tags %}
{% load crispy_forms_tags %}


<div class="clients-form">

  <form method="POST" id="form_client" enctype="multipart/form-data">
    {% csrf_token %}

    <p class="h2 text-center">Cadastro de Clientes<p>

    <!-- Forms -->
    <div class="row pb-3">
      <div class="card">
        <h5 class="card-header">Registros automáticos (Read only)</h5>
        <div class="card-body">
          <div class="row">
            {% if object.id %}
              <div class="form-group col-md-1">
                <label for="id">ID</label>
                <input type="text" class="form-control clients-form__input-entry clients-form__input-id"
                name="id" id="id" value="{{ object.id }}" maxlength="8" disabled>
              </div>
            {% endif %}

            <div class="form-group col-md-3">
              <label for="created_by_user">Criado por: </label>
              <input type="text" id="created_by_user" class="form-control" value="{{ object.created_by_user }}" disabled>
            </div>

            <div class="form-group col-md-3">
              <label for="update_by">Ultima atualização por: </label>
              <input type="text" id="update_by" class="form-control" value="{{ object.update_by }}" disabled>
            </div>

            <div class="form-group col-md-3">
              <label for="id">Data e hora da ultima atualização:</label>
              <input type="text" class="form-control" value="{{ object.update_at }}" disabled>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Dados pessoais -->
    <div class="row pb-3">
      <div class="card">
        <h5 class="card-header">Dados pessoais</h5>
        <div class="card-body">

          <div class="row pb-3">

            <div class="form-group col-md-2">
              {% if object.photo %}
                <img class="rounded-circle clients-form__photo-thumb modal__open-photo"
              src="{{ media_url }}{{ object.photo }}" alt="{{ object.photo | default_if_none:'' }}">
              {% else %}
                <img class="rounded-circle clients-form__photo-thumb modal__open-photo"
              src="{{ media_url }}default.png" alt="{{ object.photo }}">
              {% endif %}

              {% if not is_details %}
              <label for="client__upload-photo" class="border p-1 rounded-2 bg-default clients-form__btn-edit-photo">
                <span class="fas fa-pencil-alt" aria-hidden="true">&nbsp;Alterar</span>
                <input id="client__upload-photo" class="form-control" type="file" accept="images/*"
                name="photo" style="display:none">
              </label>
              {% endif %}
            </div>


            <div class="form-group col-md-3">
              <label>Cliente Físico/Juridico:</label>
              <div class="input-group">
                {% if is_details %}
									<select class="form-select clients-form__client_type" disabled>
										<option>{{ object.get_client_type_display }}</option>
									</select>
                {% else %}
									{{ form.client_type | as_crispy_field }}
                {% endif %}
								{% client_mask_cpf_cnpj object.client_type as mask_cpf_cnpj %}
								{% if is_details %}
									<input class="form-control clients-form__input-cpf-cnpj" type="text"
                    data-mask="{{ mask_cpf_cnpj }}" value="{{ object.cpf_cnpj | default_if_none:'' }}" disabled>
								{% else %}
									{{ form.cpf_cnpj | as_crispy_field }}
								{% endif %}
                <!-- {% if form.cpf_cnpj.errors %}
                  <small class="form-text text-danger">{{ form.cpf_cnpj.errors }}</small>
                {% endif %} -->
              </div>
            </div>

						<div class="col-md-4">
							{% if object.client_type == "cnpj" %}
								<label>Razão Social:</label>
							{% else %}
								<label>Nome:</label>
							{% endif %}
							{% if object.name_corporate and is_details %}
								<input class="form-control" type="text" value="{{ object.name_corporate | title | default_if_none:'' }}" disabled>
							{% else %}
								{{ form.name_corporate | as_crispy_field }}
							{% endif %}
						</div>

						<div class="form-group col-md-2">
							<label>Data Nasc/Abert:</label>
							{% if object.birth_date and is_details %}
								<input class="form-control" type="date" value="{{ object.birth_date | date:'Y-m-d' }}" disabled>
							{% else %}
								{{ form.birth_date | as_crispy_field }}
							{% endif %}
            </div>

          </div>

          <div class="row">
            <div class="form-group col-md-2">
              <label>Sexo:</label>
              {% if is_details %}
                <select class="form-select clients-form__sex" disabled>
                  <option value="{{ object.sex }}" selected>{{ object.get_sex_display }}</option>
                </select>
              {% else %}
                {{ form.sex | as_crispy_field }}
              {% endif %}
            </div>

            <div class="form-group col-md-2">
              <label>RG:</label>
							{% if is_details %}
              	<input class="form-control" type="text" value="{{ object.rg | default_if_none:'' }}" disabled>
							{% else %}
								{{ form.rg | as_crispy_field }}
							{% endif %}
              <!-- {% if form.errors %}
                <small id="id_rg" class="form-text text-danger">{{ form.rg.errors }}</small>
              {% endif %} -->
            </div>

            <div class="form-group col-md-3">
              <label>E-Mail:</label>
							{% if is_details %}
              	<input class="form-control" type="text" value="{{ object.email | default_if_none:'' }}" disabled>
							{% else %}
								{{ form.email | as_crispy_field }}
							{% endif %}
            </div>

            <div class="form-group col-md-2">
              <label>Celular:</label>
							{% if is_details %}
              	<input class="form-control" type="text"  data-mask="(00) 00000-0000"
								value="{{ object.cell_phone | default_if_none:'' }}" disabled>
							{% else %}
								{{ form.cell_phone | as_crispy_field }}
							{% endif %}
            </div>


            <div class="form-group col-md-2">
              <label>Telefone:</label>
							{% if is_details %}
              	<input class="form-control" type="text"  data-mask="(00) 0000-0000"
								value="{{ object.phone | default_if_none:'' }}" disabled>
							{% else %}
								{{ form.phone | as_crispy_field }}
							{% endif %}
            </div>
          </div>

        </div>
      </div>
    </div>

    <!-- Endereços -->
		{% client_html_obj_disable is_details as disabled %}
    <div class="row pb-3">
      <div class="card">
        <h5 class="card-header">Endereços</h5>
        <div class="card-body">
          <div class="row">

            <div class="form-group col-md-2">
              <label>CEP:</label>
              <div class="input-group mb-3">
                <input type="text" class="form-control" data-mask="00000-000" placeholder="00000-000"
                id="id_cep" name="cep" value="{{ object.cep | default_if_none:'' }}"
								required {{ disabled }}>
                <button class="btn btn-primary" type="button" id="search_cep" {{ disabled }}>
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </div>
            </div>

            <div class="form-group col-md-4">
              <label for="address">Logradouro:</label>
							{% if is_details %}
								<input class="form-control" type="text" value="{{ object.address | default_if_none:'' }}" {{ disabled }}>
							{% else %}
								{{ form.address | as_crispy_field }}
							{% endif %}
            </div>

            <div class="form-group col-md-1">
              <label>Número:</label>
							{% if is_details %}
								<input class="form-control" type="text" value="{{ object.number_address | default_if_none:'' }}" {{ disabled }}>
							{% else %}
								{{ form.number_address | as_crispy_field }}
							{% endif %}
            </div>

            <div class="form-group col-md-2">
              <label>Complemento:</label>
							{% if is_details %}
								<input class="form-control" type="text" value="{{ object.complement_address | default_if_none:'' }}" {{ disabled }}>
							{% else %}
								{{ form.complement_address | as_crispy_field }}
							{% endif %}
            </div>


            <div class="form-group col-md-3">
              <label>Cidade:</label>
							{% if is_details %}
								<input class="form-control" type="text" value="{{ object.city | default_if_none:'' }}" {{ disabled }}>
							{% else %}
								{{ form.city | as_crispy_field }}
							{% endif %}
            </div>

          </div>

          <div class="row">
            <div class="form-group col-md-3">
              <label>Bairro:</label>
							{% if is_details %}
								<input class="form-control" type="text" value="{{ object.district | default_if_none:'' }}" {{ disabled }}>
							{% else %}
								{{ form.district | as_crispy_field }}
							{% endif %}
            </div>

            <div class="form-group col-md-2">
              <label for="state">Estado:</label>
              {% if is_details %}
								<select class="form-select" {{ disabled }}>
									<option value="{{ object.state | default_if_none:'' }}" selected>
										{{ object.get_state_display }}
									</option>
								</select>
              {% else %}
								{{ form.state | as_crispy_field }}
              {% endif %}
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="card">
        <h5 class="card-header">{% trans 'Observações' %}</h5>
        <div class="card-body">
          <div class="form-group col">
						{% if is_details %}

							{% if lang == "en" %}
								{% with obs=object.obs_en %}{% endwith %}
							{% else %}
								{% with obs=object.obs_pt_br %}{% endwith %}
							{% endif %}

							<textarea class="form-control clients-form__observations" placeholder="{% trans 'Escreva uma nota para este cliente' %}"
            	{{ disabled }}>{{ object.obs }}</textarea>
						{% else %}
							{{ form.obs | as_crispy_field }}
						{% endif %}
          </div>
        </div>
      </div>
    </div>


    <!-- Buttons -->
  <div class="row pb-1 pt-4 clients-form__header">
    <div class="col-sm-12">

      {% if not is_details %}

        <button type="submit" class="btn btn-success">
          <i class="fas fa-save"></i> Salvar
        </button>

        {% if object.id %}
          <a class="btn btn-secondary" href="{% url 'client_details' object.id %}">
            <i class="fas fa-ban"></i> Cancelar
          </a>
        {% else %}
          <a class="btn btn-secondary" href="{% url 'client_read' %}">
            <i class="fas fa-ban"></i> Cancelar
          </a>
        {% endif %}

      {% else %}

        <a class="btn btn-primary" href="{% url 'client_read' %}">
          <i class="fas fa-file-alt"></i> Clientes
        </a>

        {% if perms.clients.change_clientmodel %}
          <a class="btn btn-success" href="{% url 'client_update' object.id %}">
            <i class="fas fa-pencil-alt"></i> Editar
          </a>
        {% endif %}

        {% if perms.clients.delete_clientmodel %}
          {% if object.id %}
            <button type="button" class="btn btn-danger clients-btn-delete" data-toggle="modal"
            data-target="#confirmDeleteModal">
              <span data-target="{% url 'client_delete' object.id %}">Deletar</span>
            </button>
          {% endif %}
        {% endif %}

      {% endif %}

    </div>
  </div> <!-- End Buttons -->

  </form>

</div>

<!-- Include Modal View Photo -->
{% include 'clients/modals/photo.html' %}

<!-- Include Modal Delete Record -->
{% include 'clients/modals/delete.html' %}


{% if not is_details %}
  {% include 'clients/modals/cep_not_found.html' %}
{% endif %}

{% endblock %}