crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.users.urls')),
    path('clients/', include('apps.clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/person/models.py
import re
from django.db import models
from contextlib import suppress


class PersonModel(models.Model):
    objects = None
    name = models.CharField('Nome', max_length=150, null=True)
    cpf = models.CharField('CPF', max_length=15, null=True,)
    photo = models.ImageField('Imagem',
                              default="default.png",
                              upload_to="images/upload", null=True, blank=True
                              )
    city = models.CharField('Cidade', max_length=80, null=True)
    created_at = models.DateTimeField('Data de Criação', auto_now_add=True, null=True)
    update_at = models.DateTimeField('Data de atualização', auto_now=True, null=True)

    def __str__(self):
        return f"{self.name}".title()

    class Meta:
        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"
        ordering = ["id"]

    def save(self, *args, **kwargs):

        # Remove hyphen and dot of SSA before save
        self.cpf = re.sub("[^0-9]", "", self.cpf)

        # Remove old photo after adding new
        with suppress(Exception):
            obj = PersonModel.objects.get(id=self.id)
            if obj.photo != self.photo and obj.photo != "default.png":
                obj.photo.delete(save=False)

        # Save
        super(PersonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):

        # Before deleting the record, remove the photo for the record
        self.photo.delete()
        super(PersonModel, self).delete(*args, **kwargs)

apps/person/views.py
# from django.shortcuts import render
import re
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.conf import settings
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from .models import PersonModel
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# def is_validate(obj):
#     if obj != "" and obj is not None:
#         return obj.strip()

# @method_decorator(login_required(login_url='/login/'), name='dispatch')
class PersonList(ListView):
    template_name = 'person/listing.html'
    model = PersonModel

    def get_queryset(self):
        found = self.model.objects.filter()
        q = self.request.GET.get('q')
        s_type = self.request.GET.get("s_type")
        data_number = self.request.GET.get("data_number")
        page = self.request.GET.get("page", 1)

        if data_number == "10":
            paginator = Paginator(found, 10)
        elif data_number == "25":
            paginator = Paginator(found, 25)
        elif data_number == "50":
            paginator = Paginator(found, 50)
        elif data_number == "100":
            paginator = Paginator(found, 100)
        else:
            paginator = Paginator(found, 10)

        try:
            found = paginator.page(page)
        except PageNotAnInteger:
            found = paginator.page(1)
        except EmptyPage:
            found = paginator.page(paginator.num_pages)

        if s_type == "cpf":
            q = re.sub("[^0-9]", "", q)
            found = self.model.objects.filter(cpf=q)
        elif s_type == "id":
            found = self.model.objects.filter(id=q)
        elif s_type == "name":
            found = self.model.objects.filter(name__icontains=q)

        return found

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['media_url'] = settings.MEDIA_URL
        context['data_number'] = self.request.GET.get("data_number")
        return context


class PersonCreate(LoginRequiredMixin, CreateView):
    template_name = 'person/form.html'
    login_url = reverse_lazy('login')
    fields = '__all__'
    model = PersonModel
    success_url = reverse_lazy('person_read')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['media_url'] = settings.MEDIA_URL
        return context


class PersonUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'person/form.html'
    login_url = reverse_lazy('login')
    fields = '__all__'
    model = PersonModel
    success_url = reverse_lazy('person_read')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['media_url'] = settings.MEDIA_URL
        return context


class PersonDetails(DetailView):
    model = PersonModel
    template_name = 'person/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['media_url'] = settings.MEDIA_URL
        return context


class PersonDelete(LoginRequiredMixin, DeleteView):
    model = PersonModel
    fields = '__all__'
    login_url = reverse_lazy('login')
    template_name = 'person/delete_confirm.html'
    success_url = reverse_lazy('person_read')

crud/templates/person/details.html
{% extends "base.html" %}

{% block title %} Listing {% endblock %}

{% block head %}{% endblock %}

{% block content %}

<div class="person-form">
  <form method="POST" id="form_client" enctype="multipart/form-data">

    <!-- Button -->
    <div class="row person__header">
      <div class="col-sm-12">
        <a class="btn btn-sm btn-primary" href="{% url 'person_read' %}">
          <i class="fas fa-arrow-left"></i> Back to list
        </a>
      </div>
    </div>

    <!-- Table -->
    <table class="table table-sm table-responsive-sm person-form__table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">
          Details registry
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><label for="id_id">ID</label></th>
          <td>
            <input class="person-form__input-entry person-form__input-id person-form__input-details" type="text" id="id_id" name="id"
            value="{{ object.id }}"
            maxlength="8" disabled>
            </div>
          </td>
        </tr>
        <tr>
          <th><label for="id_photo">Photo</label></th>
          <td>
            <a href="#" class="person-listing__photo-open">
              <img id="person-listing__photo-thumb" class="person-listing__photo-thumb"
              src="{{ media_url }}{{ object.photo }}" align="center" width="24"/>
            </a>
          </td>
        </tr>
        <tr>
          <th><label for="id_name">Name</label></th>
          <td>
            <input class="person-form__input-entry person-form__input-details" type="text" id="id_name" name="name"
            value="{{ object.name | title }}"
            maxlength="70" disabled>
          </td>
        </tr>
        <tr>
          <th><label for="id_cpf">CPF</label></th>
          <td>
            <input class="person-form__input-entry person-form__input-details" type="text"
            data-mask="000.000.000-00" id="id_ssa" name="cpf"
            value="{{ object.cpf }}" maxlength="15"
            placeholder="Only number" disabled>
          </td>
        </tr>
        <tr>
          <th><label for="id_city">City</label></th>
          <td>
            <input class="person-form__input-entry person-form__input-details" type="text" id="id_city" name="city"
            value="{{ object.city | title }}"
            maxlength="30" disabled>
          </td>
        </tr>
      </tbody>
    </table>
    <br>
  </form>
</div>


<!-- Include Modal View Photo -->
{% include 'person/modals/photo.html' %}

{% endblock %}

crud/templates/person/form.html
{% extends "base.html" %}

{% block title %} Formulary {% endblock %}

{% block head %}{% endblock %}

{% block content %}

<div class="person-form">
  <form method="POST" id="form_client" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Buttons -->
    <div class="row person__header">
      <div class="col-sm-12">
        <button type="submit" class="btn btn-success btn-sm">
          <i class="fas fa-save"></i> Save
        </button>
        {% if object.id %}
        <button type="button" class="btn btn-danger btn-sm person-btn-delete" data-toggle="modal"
        data-target="#confirmDeleteModal">
          <span data-target="{% url 'person_delete' object.id %}">Delete</span>
        </button>
        {% endif %}
        <a class="btn btn-secondary btn-sm" href="{% url 'person_read' %}">
          <i class="fas fa-ban"></i> Cancel
        </a>
      </div>
    </div>

    <!-- Table -->
    <table class="table table-sm table-responsive-sm person-form__table">
      <thead>
        <tr>
          <th scope="col">Person</th>
          <th scope="col">
          New registry
          </th>
        </tr>
      </thead>
      <tbody>
        {% if object.id %}
        <tr>
          <th><label for="id_id">ID</label></th>
          <td>
            <input class="person-form__input-entry person-form__input-id" type="text" id="id_id" name="id"
            value="{{ object.id }}"
            maxlength="8" disabled>
            </div>
          </td>
        </tr>
        {% endif %}
        <tr>
          <th><label for="id_photo">Photo</label></th>
          <td>
            {% if object.photo %}
            <div class="float-left mb-3 person-listing__photo-open">
              Currently:
              <img class="person-form__photo-thumb"
              src="{{ media_url }}{{ object.photo }}" alt="" width="32">
            </div>
            {% endif %}
            <div class="input-group input-group-sm mb-3">
              <div class="custom-file person-form__choose-file">
                <input class="custom-file-input" type="file" accept="images/*" name="photo" id="id_photo">
                <label class="custom-file-label person-form__choose-file-label" for="id_photo">Choose file</label>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <th><label for="id_name">Name</label></th>
          <td>
            <input class="person-form__input-entry" type="text" id="id_name" name="name"
            value="{% if object.name %}{{ object.name | title }}{% endif %}"
            maxlength="70" required>
          </td>
        </tr>
        <tr>
          <th><label for="id_cpf">CPF</label></th>
          <td>
            <input class="person-form__input-entry" type="text"
            data-mask="000.000.000-00" id="id_cpf" name="cpf"
            value="{% if object.cpf %}{{ object.cpf }}{% endif %}" maxlength="15"
            placeholder="Only number" required>
          </td>
        </tr>
        <tr>
          <th><label for="id_city">City</label></th>
          <td>
            <input class="person-form__input-entry" type="text" id="id_city" name="city"
            value="{% if object.city %}{{ object.city | title }}{% endif %}"
            maxlength="30" required>
          </td>
        </tr>
      </tbody>
    </table>
    <br>
  </form>
</div>

<!-- Include Modal View Photo -->
{% include 'person/modals/photo.html' %}

<!-- Include Modal Delete Record -->
{% include 'person/modals/delete.html' %}

{% endblock %}

crud/templates/person/listing.html
{% extends "base.html" %}

{% block title %} Listing {% endblock %}

{% block head %}{% endblock %}

{% block content %}

<div class="person-listing">
  <div class="row person-listing__header">

    <!-- Buttons -->
    <div class="col-md-4 person-listing__header-col">
      <form method="GET">
        {% if user.is_authenticated %}
        <a class="btn btn-success btn-sm" href="{% url 'person_new' %}">
          <i class="fas fa-user-plus"></i> Add
        </a>
        {% endif %}
        <a class="btn btn-primary btn-sm" href="{% url 'person_read' %}">
          <i class="fas fa-sync"></i> Refresh
        </a>
      </form>
    </div>

    <!-- Search -->
    <div class="col-md-8 d-flex flex-row-reverse person-listing__header-col">
      <form method="GET">
        <span class="person-listing__search-label">
          Search by:
        </span>
        <select name="s_type" class="custom-select custom-select-sm
        person-listing__search-select">
          <option value="id">ID</option>
          <option value="name">Name</option>
          <option value="cpf">CPF</option>
        </select>
        <input type="text" data-mask="0000000" class="person-listing__search-input" name="q"
        placeholder="Enter information">
        <button type="submit" class="btn btn-primary btn-sm person-listing__search-btn">
          <i class="fas fa-search"></i> Search
        </button>
      </form>
    </div>
  </div>

  <!-- Selector -->
  <div class="row person-listing__data-number-wrapper">
    <div class="col">
        <form method="GET" class="person-listing__data-number-form">
          <input type="hidden" name="page" value="">
          <select name="data_number" class="custom-select custom-select-sm
          person-listing__data-number" onchange=this.form.submit()>
            <option selected>Select</option>
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100">100</option>
          </select>
        </form>
    </div>
  </div>

  <!-- Table -->
  <table id="tbl_listing" class="table table-sm table-responsive-sm">
    <thead class="person__thead">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Photo</th>
        <th scope="col">Name</th>
        <th scope="col">CPF</th>
        <th scope="col">City</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for person in object_list %}
      <tr class="tbl_item">
        <th scope="row">{{ person.id }}</th>
        {% if person.photo %}
        <td>
          <div class="person-listing__photo-open">
            <img id="person-listing__photo-thumb" class="person-listing__photo-thumb"
            src="{{ media_url }}{{ person.photo }}" align="center" width="24" />
          </div>
        </td>
        {% endif %}
        <td>
          {{ person.name | title }}
        </td>
        <td>
          <span data-mask="000.000.000-00">{{ person.cpf }}</span>
        </td>
        <td>
          {{ person.city | title }}
        </td>
        <td>
          {% if user.is_authenticated %} <a class="fas fa-pencil-alt person-listing__btns" href="{% url 'person_update' person.id %}"></a>{% endif %}
          <a class="fas fa-file-alt person-listing__btns" href="{% url 'person_details' person.id %}"></a>
          {% if user.is_authenticated %} <a class="person-listing__btn-delete person-btn-delete" href="" data-toggle="modal"
          data-target="#confirmDeleteModal">
            <span class="fas fa-trash-alt person-listing__btns" data-target="{% url 'person_delete' person.id %}"></span>
          </a>{% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

<!-- Paginator -->
{% if object_list.has_other_pages %}
  <nav class="person-listing__pagination">
    <ul class="pagination justify-content-center">
      <li class="page-item person-listing__pagination-btn">
      {% if object_list.has_previous %}
        <a class="page-link" href="?page={{ object_list.previous_page_number }}&data_number={{ data_number }}"
        tabindex="-1">Previous</a>
      {% else %}
        <a class="page-link disabled">Previous</a>
      {% endif %}
      </li>
      <li class="page-item person-listing__pagination-text">
        <span class="page-link">
          {{ object_list.number }}
        </span>
      </li>
      <li class="page-item person-listing__pagination-text">
        <span class="page-link">
          of
        </span>
      </li>
      <li class="page-item person-listing__pagination-text">
        <span class="page-link">
          {{ object_list.paginator.num_pages }}
        </span>
      </li>
      <li class="page-item person-listing__pagination-btn">
        {% if object_list.has_next %}
          <a class="page-link" href="?page={{ object_list.next_page_number }}&data_number={{ data_number }}">Next</a>
        {% else %}
          <a class="page-link disabled">Next</a>
        {% endif %}
      </li>
    </ul>
  </nav>
  {% endif %}

<!-- No results -->
{% if not object_list %}
  <p class="font-weight-bold person-listing__not_found_text">No results</p>
{% endif %}

</div> <!-- End person-listing -->


<!-- Include Modal View Photo -->
{% include 'person/modals/photo.html' %}

<!-- Include Modal Delete Record -->
{% include 'person/modals/delete.html' %}

{% endblock %}